### PR TITLE
Proxy support

### PR DESCRIPTION
**Pull request by mdymczyk**
* Requires HAProxy 1.5+ to be already installed on the same machine Steam is running
* Generates HAproxy config on cluster launch/delete:
** binds on port 9999
** simple redirect based on URL path
** adds Authentication Basic header from a cookie (cookie name == cluster name)
* Generates a user/random password (username == steam username) for each new H2O cluster and starts H2O Jetty in secure mode (HashLogin) when "secure" checkbox in Steam is "on" - a base64 "user:password" token is stored in the DB (in the cluster table) 
* Adds a button to the Clusters screen for each cluster to go to them through the proxy (clicking on the name points to the clusters directly as it used to). Clicking it automatically adds a cookie (cookie name == cluster name) with the security token (from the DB) so people with the proxy URL won't be able to access it if they don't go through Steam first. 

How to test:

0) Make sure you can run `hadoop` locally (you either have a hadoop cluster set up on your machine or configured it to point to a remote one)
1) Install HAProxy 1.5+ (on mac simply `brew install haproxy`). Make sure to put it on your PATH.
2) Get this h2o-3 branch https://github.com/h2oai/h2o-3/tree/MD_context_path_doc
3) Run `./gradlew clean`
4) Get this h2o-flow branch https://github.com/h2oai/h2o-flow/tree/master
5) Run `make` in h2o-flow
6) In h2o-3 run `cp h2o-web/src/main/resources/www/flow/js/* h2o-web/lib/h2o-flow/build/js/`
7) In h2o3 build it with hadoop support https://github.com/h2oai/h2o-3/tree/MD_context_path_doc#6-building-h2o-on-hadoop
8) Pull this Steam branch, build it `go build`, clean the db `make db`
9) Run it with `sudo ./steam serve master --superuser-name=<USERNAME> --superuser-password=superuser`
10) Upload the engine you built in 6), launch a cluster (preferably with security checked)

Questions/TODOs:
1) I'm storing the token for H2O authentication in the DB, do we need a DB migration script?
2) The proxy button for each cluster is "reusing" the CSS for the trash button... Should we change that?
3) Currently using cluster name for URLs, IDs would be nicer (unique) but we get the cluster ID when its saved to the DB, which is after we start H2O - I need to pass that information to H2O so Jetty can set it as the context path, need to figure this part out.
4) We will need to add roles to cluster list so only certain people can see certain clusters.

### CODE REVIEW

**Comment by CreatureDev** [comment]
I can't seem to launch a yarn cluster off this branch
It keeps saying 'ERRORL at least one node failed to come up during cluster formation'

**Comment by CreatureDev** [comment]
I have an error building h2o-flow
unexpected string in gulpfile.coffee

**Comment by CreatureDev** [comment]
Is there a way to disable use of the proxy when launching clusters? I am getting an error that 'at least one node failed to start' when I try launching clusters in the old way, i.e. without installing haproxy or using h2o off the MD_jetty_context_path branch

**Comment by CreatureDev** [comment]
I'm also getting a 'failed to reload proxy configuration' error when launching h2o built off MD_jetty_context_path
haproxy usage is displayed as well, so it appears one of the haproxy commands is malformed

I can launch the cluster but cannot connect to it

**Comment by CreatureDev** [comment]
Was able to build h2o-flow, but that did not fix the issue with reloading the haproxy config
Clusters launch, but when attempting to go to flow through the proxy the user is unable to connect

**Comment by mdymczyk** [comment]
@CreatureDev there's no way to use old/non-proxy JARs since I'm launching with a new parameter. Do we need it? i.e. do we want to have a "proxy" button like the "security" button?

Which HAproxy version are you using, which OS and how are you running HAproxy and steam (as sudo?).

**Comment by CreatureDev** [comment]
HAproxy 1.6
I was testing it on d5, which is ubuntu 12
I will try it again on a modern release

**Comment by mdymczyk** [comment]
@CreatureDev if you havent retested yet, could you give me a few more hours? I want to push changes that will allow launching old engines (h2o without proxy support) but want to try it out once myself.

**Comment by CreatureDev** [comment]
Sounds good @mdymczyk

**Comment by mdymczyk** [comment]
@CreatureDev I pushed a few updates:

- it should now work with old h2odrivers, once without the changed context path (URL "/") - in such case the proxy button will not work, so setting the security checkbox also doesn't make sense. The only reasonable usecase here is "no security" and go to the cluster by clicking the cluster name

- the cluster status and version should now always work

- the cluster should start whether HAproxy is installed or not, of course the proxy button wont work if it's not installed but you can still get to the cluster by clicking the cluster name

- tested on my mac with HAproxy 1.6 and 1.7, anything older is pretty old and I don't think we should support it (maybe 1.5).

I did change the h2o-3 branch name in the main comment (MD_context_path_doc) so please use that one.

**Comment by CreatureDev** [comment]
`failed to reload proxy configuration` error still occurring on linux
works fine if `haproxy -f haproxy.conf` is run after launching the cluster

**Comment by mdymczyk** [comment]
Minor changes to the db and ui, will need `make db` and `make js`.

**Comment by CreatureDev** [comment]
Proxy is working, but I'm having trouble connecting to a cluster that was launched externally 
`ERR superuser RegisterCluster NOT NULL constraint failed: cluster.context_path`

**Comment by justinloyola** [comment]
LGTM.

**Pull request merged**
