### PR TITLE
Test RPM package installation

### PR DESCRIPTION
**Pull request by mmalohlava**
Test RPM installation on a plain centos6 image.

@justinloyola please verify change of Makefile.

@abal5 we will update this PR with your changes in RPM building.

### CODE REVIEW

**Comment by justinloyola** [comment]
LGTM.

**Comment by mmalohlava** [comment]
Lets keep this one open, i need to update it

**Comment by mmalohlava** [comment]
If @CreatureDev @justinloyola @abal5 are happy, i would propose to merge this branch.

**Comment by mmalohlava** [comment]
Test run is visible here: http://mr-0xb1:8080/view/Steam/job/h2o_steam_docker_rpm/16

**Comment by CreatureDev** [comment]
LGTM

**Pull request merged**
