### PR TITLE
Prediction service doc updates

### PR DESCRIPTION
**Pull request by angela0xdata**
Added the Prediction Service README as an appendix to the User Guide. Linked to this appendix from within the Making Predictions section. Also updated the text within the Making Predictions section to
highlight the purpose of the Prediction Service tool.
These changes required a minor change to the CLI appendix, which is no longer the only appendix.
Driveby fixes: Changed the background color of the help system from H2O yellow to Steam orange. Also, in the installation instructions, moved the step for starting the jetty server to BEFORE starting Steam.
Hopefully there is now less chance that this step is overlooked.

### CODE REVIEW

**Comment by justinloyola** [comment]
Can you reopen this PR into develop?

**Comment by angela0xdata** [comment]
Whoa! ... So I branched off of develop (given Magnus's recent changes). I thought this would automatically merge into develop.

**Comment by justinloyola** [comment]
Yeah, it should, this PR is made into master though.

**Comment by angela0xdata** [comment]
Okay, so going into develop wasn't automatic. Pull Request 193 should (hopefully) take care of this.

**Comment by justinloyola** [comment]
Yep, looks good. I merged #193 and I'll close this one.

**Pull request closed without merging**
